name: mica_cli
description: A sample command-line application.
version: 1.0.2+2
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  http: ^1.2.2
  io: null
  mustache_template: ^2.0.0
  path: ^1.8.0
  recase: null

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  mica_cli: mica_cli
